name: Fetch All Open Pull Request SHAs

on:
  workflow_dispatch:
  push:
    branches: '**'
  pull_request:
    branches: [ main, code-action-unification ]

jobs:
  fetch_all_pull_request_shas:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch all opened pull request numbers and merge commit SHAs
        shell: bash
        id: fetch_all_pull_requests
        run: |
          pr_info=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/redhat-developer/lsp4ij/pulls?state=open&sort=created&direction=desc&per_page=100" \
          | jq -r '.[] | "\(.number) \(.merge_commit_sha)"')
          
          while read -r pr; do
            pr_number=$(echo $pr | awk '{print $1}')
            pr_merge_sha=$(echo $pr | awk '{print $2}')
            echo "PULL_REQUEST_NUMBER=$pr_number" >> $GITHUB_ENV
            echo "PULL_REQUEST_MERGE_SHA=$pr_merge_sha" >> $GITHUB_ENV
            echo "Pull Request Number: $pr_number"
            echo "Pull Request Merge SHA: $pr_merge_sha"
          done <<< "$pr_info"

      - name: Slack Notification
        if: always() # Ensure the notification is sent regardless of job status
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Workflow ${{ github.workflow }} triggered by branch ${{ github.ref }}. PR: ${{ github.event.pull_request.html_url }}. Status: ${{ job.status }}"
          }' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}