name: cleanup caches by a branch
on:
  schedule:
    - cron: '52 15 * * 1-5'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache keys"
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | awk 'NR>1 {print $1}')
          echo "Cache keys-->: $cacheKeys"

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          REPO: ${{ github.repository }}
          BRANCH: main
