name: PR notification new
on:
  pull_request:
    types: [ opened , reopened , closed, review_request_removed, review_requested]

jobs:
  notify_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest pull request
        id: latest_pr
        run: |
          PR_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/redhat-developer/lsp4ij/pulls)
          LATEST_PR_URL=$(echo "$PR_JSON" | jq -r '.[0].html_url')
          echo "::set-output name=latest_pr_url::$LATEST_PR_URL"

      - name: Notify to Slack
        if: steps.latest_pr.outputs.latest_pr_url != 'null'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          status: success
          text: "Latest Pull Request: ${{ steps.latest_pr.outputs.latest_pr_url }}"
          secrets: |
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_CHANNEL: C070N7CG3U4