name: Fetch All Open Pull Requests with File Changes

on:
  push:
  pull_request:
    types: [reopened, opened, synchronize]

jobs:
  fetch_pull_requests_with_file_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch open pull requests
        id: fetch_prs
        run: |
          PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/MicroShed/lsp4ij/pulls?state=open" | jq -r '.[].number')
          echo "Open pull requests: $PRS"
          echo "::set-output name=PRS::$PRS"

      - name: Send PR details to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_message: "New pull request opened! Details: ${{ steps.fetch_prs.outputs.PRS }}"
