name: PR notification
on:
  pull_request:
    types: [ opened , reopened , closed, review_request_removed, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    name: PR creation
    steps:
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
            "text": "GitHub Action PR ${{ github.event_name }}: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action PR ${{ github.event_name }} recently: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
