name: Fetch All Open and Recently Closed Pull Requests using cron job

on:
  workflow_dispatch:
  push:
    branches: '**'

jobs:
  fetch_all_pull_requests_and_notify_using_condition_and_cron:
    runs-on: ubuntu-latest

    env:
      REPO: ${{ github.repository }}
      BRANCH: main
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_URL: https://api.github.com/repos/vaisakhkannan/liberty-tools-intellij/pulls
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_COPY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch recent cache
        run: |
          gh extension install actions/gh-actions-cache

          # Fetching list of cache keys....
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
          
          # Extract the most recent cache key
          mostRecentCacheKey=$(echo "$cacheKeys" | head -n 1)
          
          if [ -n "$mostRecentCacheKey" ]; then
            echo "CACHE_KEY=$mostRecentCacheKey" >> $GITHUB_ENV
          else
            echo "No recent cache key found, generating a new one......"
            echo "CACHE_KEY=${{ runner.os }}-pr-cache-${{ github.run_number }}" >> $GITHUB_ENV
          fi
          
          echo "Done"
          # 'secrets.GITHUB_TOKEN' is automatically provided by GitHub Actions for each workflow run. You don't need to manually create or manage this token.

      - name: Restore cache
        id: cache-restore
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ env.CACHE_KEY }}

      - name: Ensure cache directory exists and check if cache restored
        run: |
          mkdir -p cache
          if [ -f cache/notified_prs.json ]; then
            echo "Cache restored successfully."
            cat cache/notified_prs.json
          else
            echo "Cache not restored or file does not exist.."
          fi

      - name: Fetch all opened pull request details using condition
        id: fetch_all_pull_requests_using_condition
        run: |
          # Fetch pull request details
          pr_infos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "${{ env.API_URL }}?state=open&direction=desc&per_page=100")

          # Check if pr_infos is valid JSON
          echo "$pr_infos" | jq '.' > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Invalid JSON payload from API"
            exit 1
          fi

          echo "List of Open PRs fetched: "
          echo "$pr_infos" | jq '.[] | {number, title, user: .user.login, url: .html_url, created_at, updated_at, draft}'

          # Load previous PR data if exists
          previous_prs=$(cat cache/notified_prs.json 2>/dev/null || echo "[]")

          # Check if previous_prs is valid JSON
          echo "$previous_prs" | jq '.' > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Invalid JSON in cache/notified_prs.json"
            exit 1
          fi

          new_notified_prs=$(echo "$pr_infos" | jq '[.[] | {number, updated_at}]')
          echo "New notified prs: $new_notified_prs"

          pr_list=$(jq -n --argjson current "$pr_infos" --argjson previous "$previous_prs" '
            $current | map(select(
              .number as $num |
              ($previous | map(select(.number == $num or .updated_at > .updated_at)) | length) == 0
            ) | "\n*Pull Request* #\(.number): \(.title)\n*Created by*: \(.user.login)\n*URL*: \(.html_url)\n*Created At*: \(.created_at)\n*Last Updated At*: \(.updated_at)\(if .draft == true then "\n*Draft*: true" else "" end)\n") | join("\n")' | tr -d '"')
  
  
          echo "List of Open PRs that need to be notified in this run:"
          echo "PR List: $pr_list"
          
          # Save current PR data for future comparison
          echo "$new_notified_prs" > cache/notified_prs.json

          if [ -n "$pr_list" ]; then
            echo -e "$pr_list" > pr_list.txt
            echo "::set-output name=notify::true"
          else
            echo "::set-output name=notify::false"
          fi

      - name: Fetch closed pull requests since the last run
        id: fetch_closed_prs
        run: |
          if [ -f cache/last_run_timestamp.txt ]; then
            last_run_timestamp=$(cat cache/last_run_timestamp.txt)
          else
            last_run_timestamp=$(date -u -d "-24 hours" +%Y-%m-%dT%H:%M:%SZ)
          fi

          echo "Last run timestamp: $last_run_timestamp"

          closed_prs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "${{ env.API_URL }}?state=closed&direction=desc&per_page=100")

          echo "List of Closed PRs fetched:"
          echo "$closed_prs" | jq '.[] | {number: .number, title: .title, user: .user.login, url: .html_url, created_at: .created_at, updated_at: .updated_at, closed_at: .closed_at, draft: .draft}'

          closed_pr_list=""

          for pr_info in $(echo "$closed_prs" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${pr_info}" | base64 --decode | jq -r "${1}"
            }

            pr_number=$(_jq '.number')
            pr_title=$(_jq '.title')
            pr_user=$(_jq '.user.login')
            pr_url=$(_jq '.html_url')
            pr_closed_at=$(_jq '.closed_at')
            pr_created_at=$(_jq '.created_at')

            if [[ "$pr_closed_at" > "$last_run_timestamp" ]]; then
              closed_pr_list="${closed_pr_list}\n*Closed Pull Request* #${pr_number}: ${pr_title}\n*Closed by*: ${pr_user}\n*URL*: ${pr_url}\n*Closed At*: ${pr_closed_at}\n"
            fi
          done

          echo "Closed PR List since last cron job::"
          echo "$closed_pr_list"

          if [ -n "$closed_pr_list" ]; then
            echo -e "$closed_pr_list" > closed_pr_list.txt
            echo "::set-output name=notify_closed::true"
          else
            echo "::set-output name=notify_closed::false"
          fi      

      - name: Send Slack notification for PRs
        if: success() && (steps.fetch_all_pull_requests_using_condition.outputs.notify == 'true' || steps.fetch_closed_prs.outputs.notify_closed == 'true')
        run: |
          # Initialize PR lists
          pr_list=""
          closed_pr_list=""

          # Check if the open PRs file exists and read its content
          if [ -f pr_list.txt ]; then
            pr_list=$(cat pr_list.txt)
          fi

          # Check if the closed PRs file exists and read its content
          if [ -f closed_pr_list.txt ]; then
            closed_pr_list=$(cat closed_pr_list.txt)
          fi

          # Initialize payload blocks
          payload_blocks=()

          # Add open PRs section if not empty
          if [ -n "$pr_list" ]; then
            payload_blocks+=("{
              \"type\": \"header\",
              \"text\": {
                \"type\": \"plain_text\",
                \"text\": \"List of Open/New/Updated Pull Requests using Cron Job\"
              }
            }")
            payload_blocks+=("{
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"$pr_list\"
              }
            }")
          fi

          # Add closed PRs section if not empty
          if [ -n "$closed_pr_list" ]; then
            payload_blocks+=("{
              \"type\": \"header\",
              \"text\": {
                \"type\": \"plain_text\",
                \"text\": \"List of Pull Requests Closed Since the Last Cron Job\"
              }
            }")
            payload_blocks+=("{
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"$closed_pr_list\"
              }
            }")
          fi

          # Construct the payload
          payload=$(cat <<-EOF
          {
            "blocks": [
              $(IFS=,; echo "${payload_blocks[*]}")
            ]
          }
          EOF
          )
          # Send the payload to Slack
          curl -X POST -H 'Content-type: application/json' --data "$payload" $SLACK_WEBHOOK_URL || echo "Slack notification failed with status code: $?"

      - name: Save current timestamp
        run: |
          current_timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "$current_timestamp" > cache/last_run_timestamp.txt
          echo "Current run timestamp: $current_timestamp"

      - name: Verify Cache Save
        if: always()
        run: |
          echo "Checking saved cache content...."
          ls -l cache/
          cat cache/notified_prs.json

      - name: Save cache
        if: always()
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.os }}-pr-cache-${{ github.run_number }}

      - name: Cleanup the restored cache key
        run: |

          # Fetching list of cache keys........
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
          echo "Cache keys-->: $cacheKeys"

          # Extract the most recent cache key
          mostRecentCacheKey=$(echo "$cacheKeys" | head -n 1)

          echo "Done"
          # The permissions can be fine-tuned in the repository settings under "Settings" > "Actions" > "General" > "Workflow permissions."
          # Make sure to enable "Read and write permissions" in order to delete the cache key with "secrets.GITHUB_TOKEN". 
          # Otherwise, the repository owner will need to create a Personal Access Token (PAT) with write permissions, add it as a secret, and specify it as GH_TOKEN.

    permissions:
      actions: write

  slack-notification:
    runs-on: ubuntu-latest
    needs: fetch_all_pull_requests_and_notify_using_condition_and_cron
    env:
      WORKFLOW_BUILDER_WEBHOOK: ${{ secrets.WORKFLOW_BUILDER_WEBHOOK_COPY }}
    if: always()
    steps:
      - name: 'Slack Notification Reminder'
        run: |
          payload=$(cat <<-EOF
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "Slack Notification to perform Workflow Builder Action"
                }
              }
          EOF
          )
          curl -X POST -H 'Content-type: application/json' --data "$payload" $WORKFLOW_BUILDER_WEBHOOK || echo "Slack notification failed with status code: $?"